### ISSUE TITLE
出现了禁止标志怎么办？

### ISSUE THREAD

**Issue by shownb** [cnsilvan/deskmini310_hackintosh#1]

**Comment by shownb** [comment]
发现是Board-ID问题。我改了一下就好了。请问为什么用你的Board-ID会不行了。还有，市面上很多人的也不行。

**Comment by cnsilvan** [comment]
> 发现是Board-ID问题。我改了一下就好了。请问为什么用你的Board-ID会不行了。还有，市面上很多人的也不行。

暂时未收到其他人的反馈，检查clover版本和bios版本\设置，先关闭。
