### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by zlylong** [cnsilvan/deskmini310_hackintosh#12]
睡眠唤醒的时候HDMI还是黑屏，需要拔插HDMI线，请问这个能修复吗？

**Comment by cnsilvan** [comment]
> 睡眠唤醒的时候HDMI还是黑屏，需要拔插HDMI线，请问这个能修复吗？

你不说 我都没发现这个问题。有空看看

**Comment by cnsilvan** [comment]
> 睡眠唤醒的时候HDMI还是黑屏，需要拔插HDMI线，请问这个能修复吗？

应该是驱动bug，升级最新的 就好了。我待会发一个升级

**Comment by zlylong** [comment]
> > 睡眠唤醒的时候HDMI还是黑屏，需要拔插HDMI线，请问这个能修复吗？
> 
> 应该是驱动bug，升级最新的 就好了。我待会发一个升级

多谢
