### ISSUE TITLE
系统帧率问题

### ISSUE THREAD

**Issue by wiviam** [cnsilvan/deskmini310_hackintosh#13]
首先感谢大佬，只有用你的版本，我的机器才能正常睡眠，最近重装了big sur 采用了大佬的oc版本，但是感觉显示帧率有点低导致不顺滑，比如点击“启动台”后，左右滑动apps 特别明显，已经确认系统设置的是60hz,麻烦帮忙看下是怎么回事，thx.

**Comment by cnsilvan** [comment]
> 首先感谢大佬，只有用你的版本，我的机器才能正常睡眠，最近重装了big sur 采用了大佬的oc版本，但是感觉显示帧率有点低导致不顺滑，比如点击“启动台”后，左右滑动apps 特别明显，已经确认系统设置的是60hz,麻烦帮忙看下是怎么回事，thx.

系统问题，暂时不要升级big sur.或者等待修复。
