### ISSUE TITLE
睡眠唤醒要重启

### ISSUE THREAD

**Issue by BAYCKRC** [cnsilvan/deskmini310_hackintosh#2]
非常感谢你的分享，使我用上了mac
我用的8100cpu，睡眠后唤醒要重启，有没有什么建议？

**Comment by cnsilvan** [comment]
> 非常感谢你的分享，使我用上了mac
> 我用的8100cpu，睡眠后唤醒要重启，有没有什么建议？

把AppleALC.kext替换成VoodooHDA.kext 尝试下。

**Comment by BAYCKRC** [comment]
多谢🙏，我试试看。

**Comment by hemoely** [comment]
@GUI3315 我也是8100睡眠重启，你的问题解决了吗，是声卡驱动导致的吗？

**Comment by cnsilvan** [comment]
使用我新提交的版本即可，如果还有问题告诉我。
