### ISSUE TITLE
9100 BIOS P4.1  进系统HDMI紫屏

### ISSUE THREAD

**Issue by 631894570** [cnsilvan/deskmini310_hackintosh#3]
9100 BIOS P4.1  进系统HDMI紫屏  有办法解决么

**Comment by cnsilvan** [comment]
DP口有问题吗？

**Comment by 631894570** [comment]
DP是可以正常输出的  HDMI 如果拔掉重新插会闪2次屏才会亮  而且时间很长  依然紫屏

**Comment by cnsilvan** [comment]
> DP是可以正常输出的 HDMI 如果拔掉重新插会闪2次屏才会亮 而且时间很长 依然紫屏

我这里没发现任何问题，你试一下换一个好点的hdmi数据线，还不行的话，你可以尝试修改你的framebuffer。
