### ISSUE TITLE
重启问题

### ISSUE THREAD

**Issue by Lewin671** [cnsilvan/deskmini310_hackintosh#6]
请问重启的问题解决了吗？
我的重启的频率有点高，基本每天都有重启的情况。

**Comment by SnailDove** [comment]
> 请问重启的问题解决了吗？
> 我的重启的频率有点高，基本每天都有重启的情况。
等等楼主周末的回复，我也在等待

**Comment by cnsilvan** [comment]
我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install

**Comment by SnailDove** [comment]
> 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install

谢谢楼主反馈，笔芯！！

**Comment by Lewin671** [comment]
> 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install

谢谢楼主反馈，我也是之前在使用10.14的时候会重启。特别是高负荷(50%的占用率左右)，温度大约60度左右就很容易重启。

我今天刚升到10.15，还在测试中！

**Comment by SnailDove** [comment]
> 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install

我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？

**Comment by Elegantwolf** [comment]
> > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> 
> 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？

这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧

**Comment by SnailDove** [comment]
> > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > 
> > 
> > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> 
> 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧

15.3+你的efi  一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf  有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。

**Comment by Lewin671** [comment]
> > > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > > 
> > > 
> > > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> > 
> > 
> > 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧
> 
> 15.3+你的efi 一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf 有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。

有一个收费群，群号: 580456695。

**Comment by Lewin671** [comment]
重启的问题可以通过尝试删除whatevergreen驱动解决，我的系统是10.15.4，已经使用了两三天了，也进行了压力测试，核显加速一切都没问题，反而解决了帧缓冲导致的重启！ 此方法是我自己尝试的，大家尝试前备份好EFI！

**Comment by SnailDove** [comment]
> > > > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > > > 
> > > > 
> > > > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> > > 
> > > 
> > > 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧
> > 
> > 
> > 15.3+你的efi 一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf 有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。
> 
> 有一个收费群，群号: 580456695。

我之前看到这个群，但是不知道去哪里交智商税，所以不知道怎么申请进去，入口？

**Comment by SnailDove** [comment]
> 重启的问题可以通过尝试删除whatevergreen驱动解决，我的系统是10.15.4，已经使用了两三天了，也进行了压力测试，核显加速一切都没问题，反而解决了帧缓冲导致的重启！ 此方法是我自己尝试的，大家尝试前备份好EFI！

谢谢你提供的方法，我用黑果小兵的 15.4 287 镜像 + 这里的 efi，只有睡眠唤醒的时候屏幕不亮需要重开屏幕，其他都没问题

**Comment by Elegantwolf** [comment]
> > > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > > 
> > > 
> > > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> > 
> > 
> > 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧
> 
> 15.3+你的efi 一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf 有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。

15.3我的一切正常，不打算更新了，等今年的大更新再说吧。。

**Comment by SnailDove** [comment]
> > > > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > > > 
> > > > 
> > > > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> > > 
> > > 
> > > 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧
> > 
> > 
> > 15.3+你的efi 一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf 有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。
> 
> 15.3我的一切正常，不打算更新了，等今年的大更新再说吧。。

cool

**Comment by SnailDove** [comment]
@Lewin671  @cnsilvan  @Elegantwolf  我建了一个群 Group ID: 711821078 ，网上有两个deskmini310群，一直加不进去，在努力邀请deckmin310i的机油，我专门建了一个网页汇总310机友，欢迎讨论，欢迎加入群！！

**Comment by SnailDove** [comment]
> > > > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > > > 
> > > > 
> > > > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> > > 
> > > 
> > > 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧
> > 
> > 
> > 15.3+你的efi 一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf 有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。
> 
> 15.3我的一切正常，不打算更新了，等今年的大更新再说吧。。

我上次没表达清楚，我便携显示器HDMI和Type c口，所以一直只能用HDMI线，结果就是睡眠唤醒屏幕点不亮。DP口，不知道你们正常不？

**Comment by cnsilvan** [comment]
> > > > > > 我没遇见过重启。10.14的时候一周可能遇到一次重启，10.15一次没遇见。升级系统的时候需要重启多次选择install
> > > > > 
> > > > > 
> > > > > 我这样15.4 287使用你的efi装机成功，没有睡眠问题，感谢。可是**有一个问题**：就是睡眠唤醒或者开机的时候需要重新开关机屏幕，屏幕才能正常显示，楼主有解决方案吗？
> > > > 
> > > > 
> > > > 这个爬远景有很多人有相同问题。是15.4系统出现的问题，而且基本都是uhd630用户，用beta版本的whatevergreen似乎可以解决（注意是似乎，并不是所有人都通过这个方法解决了问题），但是作者并不是很建议这么做，我已经退回15.3，再等等吧
> > > 
> > > 
> > > 15.3+你的efi 一切都正常吗？另外 @Lewin671 @cnsilvan @Elegantwolf 有机友群介绍吗，大家一起打酱油，嘻嘻。github上这么多deskmini 310黑果。
> > 
> > 
> > 15.3我的一切正常，不打算更新了，等今年的大更新再说吧。。
> 
> 我上次没表达清楚，我便携显示器HDMI和Type c口，所以一直只能用HDMI线，结果就是睡眠唤醒屏幕点不亮。DP口，不知道你们正常不？

拔插一次。另外 温度高维持太久确实容易导致deskmini310重启，不确定是硬件还是软件导致。
