### ISSUE TITLE
hdmi音频不能输出

### ISSUE THREAD

**Issue by SnailDove** [cnsilvan/deskmini310_hackintosh#7]
我测试这里的EFI的结果是HDMI音频输出有问题，仅供大家参考

**Comment by cnsilvan** [comment]
由于applealc之前版本兼容问题，我关闭了hdmi音频的输出，否则睡眠唤醒会重启。由于没有空测试新的版本是否修复该问题，如果你们测试已经修复，可以反馈。

**Comment by SnailDove** [comment]
> 由于applealc之前版本兼容问题，我关闭了hdmi音频的输出，否则睡眠唤醒会重启。由于没有空测试新的版本是否修复该问题，如果你们测试已经修复，可以反馈。

15.4 可以用
