### ISSUE TITLE
您好，这份EFI可以用在i5 8500上吗，其他配置都一样

### ISSUE THREAD

**Issue by skylark36** [cnsilvan/deskmini310_hackintosh#9]

**Comment by SnailDove** [comment]
可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU

**Comment by skylark36** [comment]
> 可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU

好多人，感谢

**Comment by Elegantwolf** [comment]
> 可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU

带k也可以其实，只是有点浪费，我用的9600k，主频也只能到4.3而已

**Comment by SnailDove** [comment]
> > 可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU
> 
> 带k也可以其实，只是有点浪费，我用的9600k，主频也只能到4.3而已

！！你真是6！！单核4.3还是全核4.3不降频？

**Comment by SnailDove** [comment]
> > 可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU
> 
> 带k也可以其实，只是有点浪费，我用的9600k，主频也只能到4.3而已

你的hdmi口睡醒会黑屏吗？15.4版本苹果

**Comment by skylark36** [comment]
> > > 可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU
> > 
> > 
> > 带k也可以其实，只是有点浪费，我用的9600k，主频也只能到4.3而已
> 
> 你的hdmi口睡醒会黑屏吗？15.4版本苹果

我的hdmi会黑屏。
BTY，你们的风扇会变频吗？我的风扇一直在转，我的风扇型号也是ID-COOLING IS40x

**Comment by SnailDove** [comment]
> > > > 可以的 我用过，楼主就是把hdmi音频口关了。deskmini-h310可以上8 9代intel的不带k不带f的CPU
> > > 
> > > 
> > > 带k也可以其实，只是有点浪费，我用的9600k，主频也只能到4.3而已
> > 
> > 
> > 你的hdmi口睡醒会黑屏吗？15.4版本苹果
> 
> 我的hdmi会黑屏。
> BTY，你们的风扇会变频吗？我的风扇一直在转，我的风扇型号也是ID-COOLING IS40x

HDMI口已经解决
